[phases.setup]
nixPkgs = ["python310", "playwright-driver-chromium"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium",
  "playwright install-deps"
]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
